/** Single-source generator. Run: node tokens/generate-tokens.mjs from the bundle root. */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const dir = path.dirname(fileURLToPath(import.meta.url));
const source = JSON.parse(fs.readFileSync(path.join(dir, 'cosmik.source.json'), 'utf8'));
const modes = {};
const canonical = Object.keys(source.semantic.dark).sort().join('|');
for (const [mode, aliases] of Object.entries(source.semantic)) {
  if (Object.keys(aliases).sort().join('|') !== canonical) throw new Error(`Incomplete ${mode} semantic map`);
  modes[mode] = Object.fromEntries(Object.entries(aliases).map(([key, alias]) => {
    if (!source.primitives[alias]) throw new Error(`Unknown primitive ${alias}`);
    return [key, source.primitives[alias]];
  }));
}
const output = { name: source.name, version: source.version, status: source.status,
  description: 'Resolved semantic tokens. Use semantic tokens in components; primitives are reference values, not theme roles. All dimensions assume a 16px browser root. All-caps tracking is for labels only.',
  primitives: source.primitives, semantic: modes, aliases: source.semantic,
  space: source.space, layout: source.layout, type: source.type, motion: source.motion };
fs.writeFileSync(path.join(dir, 'cosmik.json'), JSON.stringify(output, null, 2) + '\n');
let css = `/* Cosmik ${source.version} — PROPOSED. Generated by generate-tokens.mjs from cosmik.source.json. */\n`;
css += ':root {\n';
for (const [key, val] of Object.entries(source.primitives)) css += `  --c-primitive-${key}: ${val};\n`;
for (const group of ['space', 'layout', 'motion']) {
  for (const [key, val] of Object.entries(source[group])) css += `  --c-${group}-${key}: ${val};\n`;
}
for (const [role, values] of Object.entries(source.type)) {
  for (const [key, val] of Object.entries(values)) {
    const property = key.replace(/[A-Z]/g, m => `-${m.toLowerCase()}`);
    css += `  --c-type-${role}-${property}: ${key === 'fontFamily' ? JSON.stringify(val) : val};\n`;
  }
}
css += '}\n';
for (const [mode, aliases] of Object.entries(source.semantic)) {
  css += `\n${mode === 'dark' ? ':root, ' : ''}[data-theme="${mode}"] {\n  color-scheme: ${mode};\n`;
  for (const [key, alias] of Object.entries(aliases)) css += `  --c-${key}: var(--c-primitive-${alias});\n`;
  css += '}\n';
}
css += '\n@media (prefers-reduced-motion: reduce) {\n  :root { --c-motion-duration: var(--c-motion-reduced-duration); }\n}\n';
fs.writeFileSync(path.join(dir, 'cosmik.css'), css);
console.log(`Generated cosmik.css and cosmik.json from one source; ${canonical.split('|').length} semantic roles × ${Object.keys(modes).length} complete modes.`);
