// Cosmik 0.3.0 — APPROVED. Generated by scripts/generate-tokens.mjs from tokens/cosmik/source.json; do not edit.
// Dependency-free: include with `#[path = "…/cosmik_tokens.rs"] mod cosmik_tokens;` or copy into a crate.
// Colours: hex, straight-alpha sRGB floats and linear-light floats, each [r, g, b, a] in 0..=1.
// Lengths: logical pixels at a 16 px root. Letter spacing: fraction of the font size.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Color {
    pub hex: &'static str,
    pub srgb: [f32; 4],
    pub linear: [f32; 4],
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct TypeRole {
    pub font_family: &'static str,
    pub font_weight: u16,
    pub font_size: f32,
    pub line_height: f32,
    pub letter_spacing: f32,
    pub uppercase: bool,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Elevation {
    pub surface: Color,
    pub shadow_color: Color,
    pub offset_x: f32,
    pub offset_y: f32,
    pub blur: f32,
    pub spread: f32,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Theme {
    pub bg: Color,
    pub surface: Color,
    pub raised: Color,
    pub text: Color,
    pub muted: Color,
    pub border: Color,
    pub divider: Color,
    pub focus: Color,
    pub link: Color,
    pub link_hover: Color,
    pub link_active: Color,
    pub on_selected: Color,
    pub selected: Color,
    pub action_primary: Color,
    pub action_primary_hover: Color,
    pub action_primary_active: Color,
    pub action_primary_fg: Color,
    pub action_secondary: Color,
    pub action_secondary_hover: Color,
    pub action_secondary_active: Color,
    pub action_secondary_fg: Color,
    pub input_bg: Color,
    pub input_fg: Color,
    pub input_placeholder: Color,
    pub disabled_bg: Color,
    pub disabled_fg: Color,
    pub disabled_border: Color,
    pub status_fg: Color,
    pub status_bg: Color,
    pub status_border: Color,
    pub divider_strong: Color,
    pub ornament: Color,
    pub ornament_faint: Color,
    pub ornament_text: Color,
    pub media_placeholder: Color,
    pub scrim: Color,

}

pub mod primitive {
    use super::Color;
    pub const BLACK: Color = Color { hex: "#000000", srgb: [0.0, 0.0, 0.0, 1.0], linear: [0.0, 0.0, 0.0, 1.0] };
    pub const PAPER: Color = Color { hex: "#F6F5F0", srgb: [0.964706, 0.960784, 0.941176, 1.0], linear: [0.921582, 0.913099, 0.871367, 1.0] };
    pub const WHITE: Color = Color { hex: "#FFFFFF", srgb: [1.0, 1.0, 1.0, 1.0], linear: [1.0, 1.0, 1.0, 1.0] };
    pub const SURFACE_DARK: Color = Color { hex: "#121212", srgb: [0.070588, 0.070588, 0.070588, 1.0], linear: [0.006049, 0.006049, 0.006049, 1.0] };
    pub const RAISED_DARK: Color = Color { hex: "#1F1F1F", srgb: [0.121569, 0.121569, 0.121569, 1.0], linear: [0.013702, 0.013702, 0.013702, 1.0] };
    pub const LIGHT_SOFT: Color = Color { hex: "#E8E7E3", srgb: [0.909804, 0.905882, 0.890196, 1.0], linear: [0.806952, 0.799103, 0.768151, 1.0] };
    pub const MUTED_DARK: Color = Color { hex: "#A3A3A3", srgb: [0.639216, 0.639216, 0.639216, 1.0], linear: [0.366253, 0.366253, 0.366253, 1.0] };
    pub const MUTED_LIGHT: Color = Color { hex: "#666666", srgb: [0.4, 0.4, 0.4, 1.0], linear: [0.132868, 0.132868, 0.132868, 1.0] };
    pub const BORDER_FUNCTIONAL: Color = Color { hex: "#767676", srgb: [0.462745, 0.462745, 0.462745, 1.0], linear: [0.181164, 0.181164, 0.181164, 1.0] };
    pub const DECORATIVE_DARK: Color = Color { hex: "#303030", srgb: [0.188235, 0.188235, 0.188235, 1.0], linear: [0.029557, 0.029557, 0.029557, 1.0] };
    pub const GRAPHITE: Color = Color { hex: "#414141", srgb: [0.254902, 0.254902, 0.254902, 1.0], linear: [0.052861, 0.052861, 0.052861, 1.0] };
    pub const ORNAMENT_DARK: Color = Color { hex: "#252525", srgb: [0.145098, 0.145098, 0.145098, 1.0], linear: [0.0185, 0.0185, 0.0185, 1.0] };
    pub const ORNAMENT_DARK_FAINT: Color = Color { hex: "#181818", srgb: [0.094118, 0.094118, 0.094118, 1.0], linear: [0.009134, 0.009134, 0.009134, 1.0] };
    pub const MEDIA_DARK: Color = Color { hex: "#111111", srgb: [0.066667, 0.066667, 0.066667, 1.0], linear: [0.005605, 0.005605, 0.005605, 1.0] };
    pub const RULE_LIGHT: Color = Color { hex: "#C6C5C0", srgb: [0.776471, 0.772549, 0.752941, 1.0], linear: [0.564712, 0.55834, 0.527115, 1.0] };
    pub const PAPER_SHADE: Color = Color { hex: "#EFEEE9", srgb: [0.937255, 0.933333, 0.913725, 1.0], linear: [0.863157, 0.854993, 0.814847, 1.0] };
    pub const SCRIM_DARK: Color = Color { hex: "#000000B8", srgb: [0.0, 0.0, 0.0, 0.721569], linear: [0.0, 0.0, 0.0, 0.721569] };
    pub const SCRIM_LIGHT: Color = Color { hex: "#0000007A", srgb: [0.0, 0.0, 0.0, 0.478431], linear: [0.0, 0.0, 0.0, 0.478431] };
}

pub const DARK: Theme = Theme {
    bg: primitive::BLACK,
    surface: primitive::SURFACE_DARK,
    raised: primitive::RAISED_DARK,
    text: primitive::PAPER,
    muted: primitive::MUTED_DARK,
    border: primitive::BORDER_FUNCTIONAL,
    divider: primitive::DECORATIVE_DARK,
    focus: primitive::PAPER,
    link: primitive::PAPER,
    link_hover: primitive::WHITE,
    link_active: primitive::PAPER,
    on_selected: primitive::BLACK,
    selected: primitive::PAPER,
    action_primary: primitive::PAPER,
    action_primary_hover: primitive::WHITE,
    action_primary_active: primitive::LIGHT_SOFT,
    action_primary_fg: primitive::BLACK,
    action_secondary: primitive::SURFACE_DARK,
    action_secondary_hover: primitive::RAISED_DARK,
    action_secondary_active: primitive::BLACK,
    action_secondary_fg: primitive::PAPER,
    input_bg: primitive::BLACK,
    input_fg: primitive::PAPER,
    input_placeholder: primitive::MUTED_DARK,
    disabled_bg: primitive::RAISED_DARK,
    disabled_fg: primitive::MUTED_DARK,
    disabled_border: primitive::BORDER_FUNCTIONAL,
    status_fg: primitive::PAPER,
    status_bg: primitive::RAISED_DARK,
    status_border: primitive::BORDER_FUNCTIONAL,
    divider_strong: primitive::GRAPHITE,
    ornament: primitive::ORNAMENT_DARK,
    ornament_faint: primitive::ORNAMENT_DARK_FAINT,
    ornament_text: primitive::GRAPHITE,
    media_placeholder: primitive::MEDIA_DARK,
    scrim: primitive::SCRIM_DARK,
};

pub const LIGHT: Theme = Theme {
    bg: primitive::PAPER,
    surface: primitive::WHITE,
    raised: primitive::LIGHT_SOFT,
    text: primitive::BLACK,
    muted: primitive::MUTED_LIGHT,
    border: primitive::BORDER_FUNCTIONAL,
    divider: primitive::LIGHT_SOFT,
    focus: primitive::BLACK,
    link: primitive::BLACK,
    link_hover: primitive::SURFACE_DARK,
    link_active: primitive::RAISED_DARK,
    on_selected: primitive::WHITE,
    selected: primitive::BLACK,
    action_primary: primitive::BLACK,
    action_primary_hover: primitive::SURFACE_DARK,
    action_primary_active: primitive::RAISED_DARK,
    action_primary_fg: primitive::WHITE,
    action_secondary: primitive::WHITE,
    action_secondary_hover: primitive::LIGHT_SOFT,
    action_secondary_active: primitive::PAPER,
    action_secondary_fg: primitive::BLACK,
    input_bg: primitive::WHITE,
    input_fg: primitive::BLACK,
    input_placeholder: primitive::MUTED_LIGHT,
    disabled_bg: primitive::LIGHT_SOFT,
    disabled_fg: primitive::MUTED_LIGHT,
    disabled_border: primitive::BORDER_FUNCTIONAL,
    status_fg: primitive::BLACK,
    status_bg: primitive::LIGHT_SOFT,
    status_border: primitive::BORDER_FUNCTIONAL,
    divider_strong: primitive::RULE_LIGHT,
    ornament: primitive::LIGHT_SOFT,
    ornament_faint: primitive::PAPER_SHADE,
    ornament_text: primitive::RULE_LIGHT,
    media_placeholder: primitive::LIGHT_SOFT,
    scrim: primitive::SCRIM_LIGHT,
};

pub mod space {
    pub const N2: f32 = 8.0;
    pub const N4: f32 = 16.0;
    pub const N6: f32 = 24.0;
    pub const N8: f32 = 32.0;
    pub const N12: f32 = 48.0;
    pub const N16: f32 = 64.0;
    pub const N24: f32 = 96.0;
    pub const BASE: f32 = 4.0;
}

pub mod radius {
    pub const SM: f32 = 2.0;
    pub const MD: f32 = 4.0;
    pub const FULL: f32 = 9999.0;
}

pub mod breakpoint {
    pub const COMPACT: f32 = 720.0;
    pub const NARROW: f32 = 380.0;
}

pub mod layout {
    pub const RADIUS: f32 = 4.0;
    pub const GUTTER: f32 = 24.0;
    pub const MAX_CONTENT: f32 = 1120.0;
    /// Reading measure in characters.
    pub const LINE_CHARS: u32 = 65;
    pub const CONTROL_MIN: f32 = 44.0;
    pub const FOCUS_WIDTH: f32 = 2.0;
    pub const FOCUS_OFFSET: f32 = 2.0;
}

pub mod typography {
    use super::TypeRole;
    pub const BODY: TypeRole = TypeRole { font_family: "Inter", font_weight: 400, font_size: 17.0, line_height: 1.55, letter_spacing: 0.0, uppercase: false };
    pub const DISPLAY: TypeRole = TypeRole { font_family: "Inter", font_weight: 600, font_size: 48.0, line_height: 1.1, letter_spacing: 0.0, uppercase: false };
    pub const DISPLAY_SMALL: TypeRole = TypeRole { font_family: "Inter", font_weight: 600, font_size: 34.0, line_height: 1.15, letter_spacing: 0.0, uppercase: false };
    pub const SECTION: TypeRole = TypeRole { font_family: "Inter", font_weight: 600, font_size: 30.0, line_height: 1.2, letter_spacing: 0.0, uppercase: false };
    pub const CARD: TypeRole = TypeRole { font_family: "Inter", font_weight: 600, font_size: 22.0, line_height: 1.3, letter_spacing: 0.0, uppercase: false };
    pub const CONTROL: TypeRole = TypeRole { font_family: "Inter", font_weight: 500, font_size: 15.0, line_height: 1.4, letter_spacing: 0.0, uppercase: false };
    pub const LABEL: TypeRole = TypeRole { font_family: "IBM Plex Mono", font_weight: 400, font_size: 14.0, line_height: 1.5, letter_spacing: 0.06, uppercase: true };
    pub const IDENTITY_LABEL: TypeRole = TypeRole { font_family: "Inter", font_weight: 500, font_size: 20.0, line_height: 1.3, letter_spacing: 0.0, uppercase: false };
}

pub mod motion {
    pub const DURATION_MS: u32 = 140;
    pub const REDUCED_DURATION_MS: u32 = 0;
    /// Cubic-bezier control points [x1, y1, x2, y2].
    pub const EASING: [f32; 4] = [0.0, 0.0, 0.58, 1.0];
}
