// Cosmik · HPLX 0.1.0 — PROPOSED. Generated by scripts/generate-tokens.mjs from tokens/hplx/family.json over tokens/cosmik/source.json; do not edit.
// Dependency-free: include with `#[path = "…/hplx_tokens.rs"] mod hplx_tokens;` or copy into a crate.
// Colours: hex, straight-alpha sRGB floats and linear-light floats, each [r, g, b, a] in 0..=1.
// Lengths: logical pixels at a 16 px root. Letter spacing: fraction of the font size.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Color {
    pub hex: &'static str,
    pub srgb: [f32; 4],
    pub linear: [f32; 4],
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct TypeRole {
    pub font_family: &'static str,
    pub font_weight: u16,
    pub font_size: f32,
    pub line_height: f32,
    pub letter_spacing: f32,
    pub uppercase: bool,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Elevation {
    pub surface: Color,
    pub shadow_color: Color,
    pub offset_x: f32,
    pub offset_y: f32,
    pub blur: f32,
    pub spread: f32,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Theme {
    pub bg: Color,
    pub surface: Color,
    pub raised: Color,
    pub text: Color,
    pub muted: Color,
    pub border: Color,
    pub divider: Color,
    pub focus: Color,
    pub link: Color,
    pub link_hover: Color,
    pub link_active: Color,
    pub on_selected: Color,
    pub selected: Color,
    pub action_primary: Color,
    pub action_primary_hover: Color,
    pub action_primary_active: Color,
    pub action_primary_fg: Color,
    pub action_secondary: Color,
    pub action_secondary_hover: Color,
    pub action_secondary_active: Color,
    pub action_secondary_fg: Color,
    pub input_bg: Color,
    pub input_fg: Color,
    pub input_placeholder: Color,
    pub disabled_bg: Color,
    pub disabled_fg: Color,
    pub disabled_border: Color,
    pub status_fg: Color,
    pub status_bg: Color,
    pub status_border: Color,
    pub divider_strong: Color,
    pub ornament: Color,
    pub ornament_faint: Color,
    pub ornament_text: Color,
    pub media_placeholder: Color,
    pub scrim: Color,
    pub accent: Color,
    pub shadow: Color,
    pub status_error_fg: Color,
    pub status_error_bg: Color,
    pub status_error_border: Color,
    pub status_warning_fg: Color,
    pub status_warning_bg: Color,
    pub status_warning_border: Color,
    pub status_success_fg: Color,
    pub status_success_bg: Color,
    pub status_success_border: Color,
    pub status_info_fg: Color,
    pub status_info_bg: Color,
    pub status_info_border: Color,
    pub elevation_1: Elevation,
    pub elevation_2: Elevation,
    pub elevation_3: Elevation,
}

pub mod primitive {
    use super::Color;
    pub const BLACK: Color = Color { hex: "#000000", srgb: [0.0, 0.0, 0.0, 1.0], linear: [0.0, 0.0, 0.0, 1.0] };
    pub const PAPER: Color = Color { hex: "#F6F5F0", srgb: [0.964706, 0.960784, 0.941176, 1.0], linear: [0.921582, 0.913099, 0.871367, 1.0] };
    pub const WHITE: Color = Color { hex: "#FFFFFF", srgb: [1.0, 1.0, 1.0, 1.0], linear: [1.0, 1.0, 1.0, 1.0] };
    pub const SURFACE_DARK: Color = Color { hex: "#121212", srgb: [0.070588, 0.070588, 0.070588, 1.0], linear: [0.006049, 0.006049, 0.006049, 1.0] };
    pub const RAISED_DARK: Color = Color { hex: "#1F1F1F", srgb: [0.121569, 0.121569, 0.121569, 1.0], linear: [0.013702, 0.013702, 0.013702, 1.0] };
    pub const LIGHT_SOFT: Color = Color { hex: "#E8E7E3", srgb: [0.909804, 0.905882, 0.890196, 1.0], linear: [0.806952, 0.799103, 0.768151, 1.0] };
    pub const MUTED_DARK: Color = Color { hex: "#A3A3A3", srgb: [0.639216, 0.639216, 0.639216, 1.0], linear: [0.366253, 0.366253, 0.366253, 1.0] };
    pub const MUTED_LIGHT: Color = Color { hex: "#666666", srgb: [0.4, 0.4, 0.4, 1.0], linear: [0.132868, 0.132868, 0.132868, 1.0] };
    pub const BORDER_FUNCTIONAL: Color = Color { hex: "#767676", srgb: [0.462745, 0.462745, 0.462745, 1.0], linear: [0.181164, 0.181164, 0.181164, 1.0] };
    pub const DECORATIVE_DARK: Color = Color { hex: "#303030", srgb: [0.188235, 0.188235, 0.188235, 1.0], linear: [0.029557, 0.029557, 0.029557, 1.0] };
    pub const GRAPHITE: Color = Color { hex: "#414141", srgb: [0.254902, 0.254902, 0.254902, 1.0], linear: [0.052861, 0.052861, 0.052861, 1.0] };
    pub const ORNAMENT_DARK: Color = Color { hex: "#252525", srgb: [0.145098, 0.145098, 0.145098, 1.0], linear: [0.0185, 0.0185, 0.0185, 1.0] };
    pub const ORNAMENT_DARK_FAINT: Color = Color { hex: "#181818", srgb: [0.094118, 0.094118, 0.094118, 1.0], linear: [0.009134, 0.009134, 0.009134, 1.0] };
    pub const MEDIA_DARK: Color = Color { hex: "#111111", srgb: [0.066667, 0.066667, 0.066667, 1.0], linear: [0.005605, 0.005605, 0.005605, 1.0] };
    pub const RULE_LIGHT: Color = Color { hex: "#C6C5C0", srgb: [0.776471, 0.772549, 0.752941, 1.0], linear: [0.564712, 0.55834, 0.527115, 1.0] };
    pub const PAPER_SHADE: Color = Color { hex: "#EFEEE9", srgb: [0.937255, 0.933333, 0.913725, 1.0], linear: [0.863157, 0.854993, 0.814847, 1.0] };
    pub const SCRIM_DARK: Color = Color { hex: "#000000B8", srgb: [0.0, 0.0, 0.0, 0.721569], linear: [0.0, 0.0, 0.0, 0.721569] };
    pub const SCRIM_LIGHT: Color = Color { hex: "#0000007A", srgb: [0.0, 0.0, 0.0, 0.478431], linear: [0.0, 0.0, 0.0, 0.478431] };
    pub const HPLX_INK: Color = Color { hex: "#0E0F11", srgb: [0.054902, 0.058824, 0.066667, 1.0], linear: [0.004391, 0.004777, 0.005605, 1.0] };
    pub const HPLX_PANEL: Color = Color { hex: "#131518", srgb: [0.07451, 0.082353, 0.094118, 1.0], linear: [0.006512, 0.007499, 0.009134, 1.0] };
    pub const HPLX_RAISED: Color = Color { hex: "#1E2226", srgb: [0.117647, 0.133333, 0.14902, 1.0], linear: [0.012983, 0.015996, 0.019382, 1.0] };
    pub const HPLX_BONE: Color = Color { hex: "#ECE7DD", srgb: [0.92549, 0.905882, 0.866667, 1.0], linear: [0.838799, 0.799103, 0.723055, 1.0] };
    pub const HPLX_ASH: Color = Color { hex: "#A7A196", srgb: [0.654902, 0.631373, 0.588235, 1.0], linear: [0.386429, 0.3564, 0.304987, 1.0] };
    pub const HPLX_RULE: Color = Color { hex: "#2E3339", srgb: [0.180392, 0.2, 0.223529, 1.0], linear: [0.027321, 0.033105, 0.040915, 1.0] };
    pub const HPLX_EDGE: Color = Color { hex: "#7E786E", srgb: [0.494118, 0.470588, 0.431373, 1.0], linear: [0.208637, 0.187821, 0.155926, 1.0] };
    pub const HPLX_AMBER: Color = Color { hex: "#E0A53A", srgb: [0.878431, 0.647059, 0.227451, 1.0], linear: [0.745404, 0.376262, 0.042311, 1.0] };
    pub const HPLX_AMBER_HOVER: Color = Color { hex: "#EBB75C", srgb: [0.921569, 0.717647, 0.360784, 1.0], linear: [0.83077, 0.473531, 0.107023, 1.0] };
    pub const HPLX_AMBER_ACTIVE: Color = Color { hex: "#C98F2A", srgb: [0.788235, 0.560784, 0.164706, 1.0], linear: [0.584078, 0.274677, 0.023153, 1.0] };
    pub const HPLX_TAR: Color = Color { hex: "#1A1408", srgb: [0.101961, 0.078431, 0.031373, 1.0], linear: [0.01033, 0.006995, 0.002428, 1.0] };
    pub const HPLX_VELLUM: Color = Color { hex: "#F3EFE6", srgb: [0.952941, 0.937255, 0.901961, 1.0], linear: [0.896269, 0.863157, 0.791298, 1.0] };
    pub const HPLX_PARCHMENT: Color = Color { hex: "#E7E0D2", srgb: [0.905882, 0.878431, 0.823529, 1.0], linear: [0.799103, 0.745404, 0.64448, 1.0] };
    pub const HPLX_SOOT: Color = Color { hex: "#1A1714", srgb: [0.101961, 0.090196, 0.078431, 1.0], linear: [0.01033, 0.008568, 0.006995, 1.0] };
    pub const HPLX_UMBER: Color = Color { hex: "#5C554B", srgb: [0.360784, 0.333333, 0.294118, 1.0], linear: [0.107023, 0.090842, 0.07036, 1.0] };
    pub const HPLX_RULE_LIGHT: Color = Color { hex: "#D6CFC1", srgb: [0.839216, 0.811765, 0.756863, 1.0], linear: [0.672443, 0.62396, 0.533276, 1.0] };
    pub const HPLX_EDGE_LIGHT: Color = Color { hex: "#7A7266", srgb: [0.478431, 0.447059, 0.4, 1.0], linear: [0.194618, 0.168269, 0.132868, 1.0] };
    pub const HPLX_AMBER_DEEP: Color = Color { hex: "#875709", srgb: [0.529412, 0.341176, 0.035294, 1.0], linear: [0.242281, 0.095307, 0.002732, 1.0] };
    pub const HPLX_AMBER_DEEP_HOVER: Color = Color { hex: "#734A07", srgb: [0.45098, 0.290196, 0.027451, 1.0], linear: [0.171441, 0.068478, 0.002125, 1.0] };
    pub const HPLX_AMBER_DEEP_ACTIVE: Color = Color { hex: "#5F3D06", srgb: [0.372549, 0.239216, 0.023529, 1.0], linear: [0.114435, 0.046665, 0.001821, 1.0] };
    pub const SHADOW_DARK: Color = Color { hex: "#00000099", srgb: [0.0, 0.0, 0.0, 0.6], linear: [0.0, 0.0, 0.0, 0.6] };
    pub const SHADOW_LIGHT: Color = Color { hex: "#00000029", srgb: [0.0, 0.0, 0.0, 0.160784], linear: [0.0, 0.0, 0.0, 0.160784] };
    pub const RED_50: Color = Color { hex: "#FAEDEB", srgb: [0.980392, 0.929412, 0.921569, 1.0], linear: [0.955973, 0.846873, 0.83077, 1.0] };
    pub const RED_200: Color = Color { hex: "#F2B8B5", srgb: [0.94902, 0.721569, 0.709804, 1.0], linear: [0.887923, 0.47932, 0.462077, 1.0] };
    pub const RED_400: Color = Color { hex: "#D0605A", srgb: [0.815686, 0.376471, 0.352941, 1.0], linear: [0.630757, 0.116971, 0.102242, 1.0] };
    pub const RED_600: Color = Color { hex: "#B3362F", srgb: [0.701961, 0.211765, 0.184314, 1.0], linear: [0.450786, 0.036889, 0.028426, 1.0] };
    pub const RED_800: Color = Color { hex: "#8A1F1A", srgb: [0.541176, 0.121569, 0.101961, 1.0], linear: [0.254152, 0.013702, 0.01033, 1.0] };
    pub const RED_950: Color = Color { hex: "#2B1615", srgb: [0.168627, 0.086275, 0.082353, 1.0], linear: [0.024158, 0.008023, 0.007499, 1.0] };
    pub const AMBER_50: Color = Color { hex: "#FAF1DE", srgb: [0.980392, 0.945098, 0.870588, 1.0], linear: [0.955973, 0.879622, 0.730461, 1.0] };
    pub const AMBER_200: Color = Color { hex: "#EDCB8C", srgb: [0.929412, 0.796078, 0.54902, 1.0], linear: [0.846873, 0.597202, 0.262251, 1.0] };
    pub const AMBER_400: Color = Color { hex: "#B08A3E", srgb: [0.690196, 0.541176, 0.243137, 1.0], linear: [0.434154, 0.254152, 0.048172, 1.0] };
    pub const AMBER_600: Color = Color { hex: "#94690F", srgb: [0.580392, 0.411765, 0.058824, 1.0], linear: [0.296138, 0.141263, 0.004777, 1.0] };
    pub const AMBER_800: Color = Color { hex: "#6A4A05", srgb: [0.415686, 0.290196, 0.019608, 1.0], linear: [0.144128, 0.068478, 0.001518, 1.0] };
    pub const AMBER_950: Color = Color { hex: "#2A2112", srgb: [0.164706, 0.129412, 0.070588, 1.0], linear: [0.023153, 0.015209, 0.006049, 1.0] };
    pub const GREEN_50: Color = Color { hex: "#E9F3EB", srgb: [0.913725, 0.952941, 0.921569, 1.0], linear: [0.814847, 0.896269, 0.83077, 1.0] };
    pub const GREEN_200: Color = Color { hex: "#A9D3B1", srgb: [0.662745, 0.827451, 0.694118, 1.0], linear: [0.396755, 0.651406, 0.439657, 1.0] };
    pub const GREEN_400: Color = Color { hex: "#4F9A63", srgb: [0.309804, 0.603922, 0.388235, 1.0], linear: [0.078187, 0.323143, 0.124772, 1.0] };
    pub const GREEN_600: Color = Color { hex: "#2F7D46", srgb: [0.184314, 0.490196, 0.27451, 1.0], linear: [0.028426, 0.205079, 0.061246, 1.0] };
    pub const GREEN_800: Color = Color { hex: "#1D5530", srgb: [0.113725, 0.333333, 0.188235, 1.0], linear: [0.012286, 0.090842, 0.029557, 1.0] };
    pub const GREEN_950: Color = Color { hex: "#13241A", srgb: [0.07451, 0.141176, 0.101961, 1.0], linear: [0.006512, 0.017642, 0.01033, 1.0] };
    pub const BLUE_50: Color = Color { hex: "#EAF0F8", srgb: [0.917647, 0.941176, 0.972549, 1.0], linear: [0.822786, 0.871367, 0.938686, 1.0] };
    pub const BLUE_200: Color = Color { hex: "#B5C7E6", srgb: [0.709804, 0.780392, 0.901961, 1.0], linear: [0.462077, 0.571125, 0.791298, 1.0] };
    pub const BLUE_400: Color = Color { hex: "#6688C0", srgb: [0.4, 0.533333, 0.752941, 1.0], linear: [0.132868, 0.246201, 0.527115, 1.0] };
    pub const BLUE_600: Color = Color { hex: "#3B66AB", srgb: [0.231373, 0.4, 0.670588, 1.0], linear: [0.043735, 0.132868, 0.40724, 1.0] };
    pub const BLUE_800: Color = Color { hex: "#1F3F73", srgb: [0.121569, 0.247059, 0.45098, 1.0], linear: [0.013702, 0.049707, 0.171441, 1.0] };
    pub const BLUE_950: Color = Color { hex: "#151D2B", srgb: [0.082353, 0.113725, 0.168627, 1.0], linear: [0.007499, 0.012286, 0.024158, 1.0] };
}

pub const DARK: Theme = Theme {
    bg: primitive::HPLX_INK,
    surface: primitive::HPLX_PANEL,
    raised: primitive::HPLX_RAISED,
    text: primitive::HPLX_BONE,
    muted: primitive::HPLX_ASH,
    border: primitive::HPLX_EDGE,
    divider: primitive::HPLX_RULE,
    focus: primitive::HPLX_AMBER,
    link: primitive::HPLX_BONE,
    link_hover: primitive::HPLX_AMBER_HOVER,
    link_active: primitive::HPLX_BONE,
    on_selected: primitive::HPLX_INK,
    selected: primitive::HPLX_BONE,
    action_primary: primitive::HPLX_AMBER,
    action_primary_hover: primitive::HPLX_AMBER_HOVER,
    action_primary_active: primitive::HPLX_AMBER_ACTIVE,
    action_primary_fg: primitive::HPLX_TAR,
    action_secondary: primitive::HPLX_PANEL,
    action_secondary_hover: primitive::HPLX_RAISED,
    action_secondary_active: primitive::HPLX_INK,
    action_secondary_fg: primitive::HPLX_BONE,
    input_bg: primitive::HPLX_INK,
    input_fg: primitive::HPLX_BONE,
    input_placeholder: primitive::HPLX_ASH,
    disabled_bg: primitive::HPLX_RAISED,
    disabled_fg: primitive::HPLX_ASH,
    disabled_border: primitive::HPLX_EDGE,
    status_fg: primitive::HPLX_BONE,
    status_bg: primitive::HPLX_RAISED,
    status_border: primitive::HPLX_EDGE,
    divider_strong: primitive::GRAPHITE,
    ornament: primitive::ORNAMENT_DARK,
    ornament_faint: primitive::ORNAMENT_DARK_FAINT,
    ornament_text: primitive::GRAPHITE,
    media_placeholder: primitive::MEDIA_DARK,
    scrim: primitive::SCRIM_DARK,
    accent: primitive::HPLX_AMBER,
    shadow: primitive::SHADOW_DARK,
    status_error_fg: primitive::RED_200,
    status_error_bg: primitive::RED_950,
    status_error_border: primitive::RED_400,
    status_warning_fg: primitive::AMBER_200,
    status_warning_bg: primitive::AMBER_950,
    status_warning_border: primitive::AMBER_400,
    status_success_fg: primitive::GREEN_200,
    status_success_bg: primitive::GREEN_950,
    status_success_border: primitive::GREEN_400,
    status_info_fg: primitive::BLUE_200,
    status_info_bg: primitive::BLUE_950,
    status_info_border: primitive::BLUE_400,
    elevation_1: Elevation { surface: primitive::HPLX_RAISED, shadow_color: primitive::SHADOW_DARK, offset_x: 0.0, offset_y: 1.0, blur: 2.0, spread: 0.0 },
    elevation_2: Elevation { surface: primitive::HPLX_RAISED, shadow_color: primitive::SHADOW_DARK, offset_x: 0.0, offset_y: 4.0, blur: 12.0, spread: 0.0 },
    elevation_3: Elevation { surface: primitive::HPLX_RAISED, shadow_color: primitive::SHADOW_DARK, offset_x: 0.0, offset_y: 12.0, blur: 32.0, spread: 0.0 },
};

pub const LIGHT: Theme = Theme {
    bg: primitive::HPLX_VELLUM,
    surface: primitive::WHITE,
    raised: primitive::HPLX_PARCHMENT,
    text: primitive::HPLX_SOOT,
    muted: primitive::HPLX_UMBER,
    border: primitive::HPLX_EDGE_LIGHT,
    divider: primitive::HPLX_RULE_LIGHT,
    focus: primitive::HPLX_AMBER_DEEP,
    link: primitive::HPLX_SOOT,
    link_hover: primitive::HPLX_AMBER_DEEP,
    link_active: primitive::HPLX_SOOT,
    on_selected: primitive::HPLX_VELLUM,
    selected: primitive::HPLX_SOOT,
    action_primary: primitive::HPLX_AMBER_DEEP,
    action_primary_hover: primitive::HPLX_AMBER_DEEP_HOVER,
    action_primary_active: primitive::HPLX_AMBER_DEEP_ACTIVE,
    action_primary_fg: primitive::WHITE,
    action_secondary: primitive::WHITE,
    action_secondary_hover: primitive::HPLX_PARCHMENT,
    action_secondary_active: primitive::HPLX_VELLUM,
    action_secondary_fg: primitive::HPLX_SOOT,
    input_bg: primitive::WHITE,
    input_fg: primitive::HPLX_SOOT,
    input_placeholder: primitive::HPLX_UMBER,
    disabled_bg: primitive::HPLX_PARCHMENT,
    disabled_fg: primitive::HPLX_UMBER,
    disabled_border: primitive::HPLX_EDGE_LIGHT,
    status_fg: primitive::HPLX_SOOT,
    status_bg: primitive::HPLX_PARCHMENT,
    status_border: primitive::HPLX_EDGE_LIGHT,
    divider_strong: primitive::RULE_LIGHT,
    ornament: primitive::LIGHT_SOFT,
    ornament_faint: primitive::PAPER_SHADE,
    ornament_text: primitive::RULE_LIGHT,
    media_placeholder: primitive::LIGHT_SOFT,
    scrim: primitive::SCRIM_LIGHT,
    accent: primitive::HPLX_AMBER_DEEP,
    shadow: primitive::SHADOW_LIGHT,
    status_error_fg: primitive::RED_800,
    status_error_bg: primitive::RED_50,
    status_error_border: primitive::RED_600,
    status_warning_fg: primitive::AMBER_800,
    status_warning_bg: primitive::AMBER_50,
    status_warning_border: primitive::AMBER_600,
    status_success_fg: primitive::GREEN_800,
    status_success_bg: primitive::GREEN_50,
    status_success_border: primitive::GREEN_600,
    status_info_fg: primitive::BLUE_800,
    status_info_bg: primitive::BLUE_50,
    status_info_border: primitive::BLUE_600,
    elevation_1: Elevation { surface: primitive::HPLX_PARCHMENT, shadow_color: primitive::SHADOW_LIGHT, offset_x: 0.0, offset_y: 1.0, blur: 2.0, spread: 0.0 },
    elevation_2: Elevation { surface: primitive::HPLX_PARCHMENT, shadow_color: primitive::SHADOW_LIGHT, offset_x: 0.0, offset_y: 4.0, blur: 12.0, spread: 0.0 },
    elevation_3: Elevation { surface: primitive::HPLX_PARCHMENT, shadow_color: primitive::SHADOW_LIGHT, offset_x: 0.0, offset_y: 12.0, blur: 32.0, spread: 0.0 },
};

pub mod space {
    pub const N2: f32 = 8.0;
    pub const N4: f32 = 16.0;
    pub const N6: f32 = 24.0;
    pub const N8: f32 = 32.0;
    pub const N12: f32 = 48.0;
    pub const N16: f32 = 64.0;
    pub const N24: f32 = 96.0;
    pub const BASE: f32 = 4.0;
}

pub mod radius {
    pub const SM: f32 = 2.0;
    pub const MD: f32 = 4.0;
    pub const FULL: f32 = 9999.0;
}

pub mod breakpoint {
    pub const COMPACT: f32 = 720.0;
    pub const NARROW: f32 = 380.0;
}

pub mod layout {
    pub const RADIUS: f32 = 4.0;
    pub const GUTTER: f32 = 24.0;
    pub const MAX_CONTENT: f32 = 1120.0;
    /// Reading measure in characters.
    pub const LINE_CHARS: u32 = 65;
    pub const CONTROL_MIN: f32 = 44.0;
    pub const FOCUS_WIDTH: f32 = 2.0;
    pub const FOCUS_OFFSET: f32 = 2.0;
}

pub mod typography {
    use super::TypeRole;
    pub const BODY: TypeRole = TypeRole { font_family: "Inter", font_weight: 400, font_size: 17.0, line_height: 1.55, letter_spacing: 0.0, uppercase: false };
    pub const DISPLAY: TypeRole = TypeRole { font_family: "Spectral", font_weight: 600, font_size: 48.0, line_height: 1.1, letter_spacing: 0.0, uppercase: false };
    pub const DISPLAY_SMALL: TypeRole = TypeRole { font_family: "Spectral", font_weight: 600, font_size: 34.0, line_height: 1.15, letter_spacing: 0.0, uppercase: false };
    pub const SECTION: TypeRole = TypeRole { font_family: "Spectral", font_weight: 600, font_size: 30.0, line_height: 1.2, letter_spacing: 0.0, uppercase: false };
    pub const CARD: TypeRole = TypeRole { font_family: "Spectral", font_weight: 600, font_size: 22.0, line_height: 1.3, letter_spacing: 0.0, uppercase: false };
    pub const CONTROL: TypeRole = TypeRole { font_family: "Inter", font_weight: 500, font_size: 15.0, line_height: 1.4, letter_spacing: 0.0, uppercase: false };
    pub const LABEL: TypeRole = TypeRole { font_family: "IBM Plex Mono", font_weight: 400, font_size: 14.0, line_height: 1.5, letter_spacing: 0.06, uppercase: true };
    pub const IDENTITY_LABEL: TypeRole = TypeRole { font_family: "Inter", font_weight: 500, font_size: 20.0, line_height: 1.3, letter_spacing: 0.0, uppercase: false };
}

pub mod motion {
    pub const DURATION_MS: u32 = 140;
    pub const REDUCED_DURATION_MS: u32 = 0;
    /// Cubic-bezier control points [x1, y1, x2, y2].
    pub const EASING: [f32; 4] = [0.0, 0.0, 0.58, 1.0];
}
